version: "2"
services:
  db:
    image: oracle/database:11.2.0.2-xe
    volumes:
      - ./oraxe/customization:/u01/app/oracle/scripts/startup
    container_name: oraxe
    shm_size: 1g
    ports:
      - 1521:1521
      - 80:8080
    environment:
      ORACLE_PWD: California1

  wfy10:
    image: jboss/wildfly:10.1.0.Final
    volumes:
      - ./wfy10/customization:/opt/jboss/wildfly/customization/
    container_name: wfy10
    entrypoint: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    ports:
      - 8080:8080
      - 9990:9990
    links:
      - db:db
    depends_on:
     - "db"

  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./keycloak/customization:/opt/jboss/keycloak/customization/
    container_name: keycloak
    entrypoint: /opt/jboss/docker-entrypoint.sh -b 0.0.0.0
    ports:
      - 18080:8080
      - 19990:9990
    environment:
      KEYCLOAK_USER: nicolas
      KEYCLOAK_PASSWORD: California1  
    links:
     - db:db
    depends_on:
     - "db"
     